### ISSUE TITLE
apps/wordpress-nginx

### ISSUE THREAD

**Issue by cloudwm** [cloudwm/installer#14]
check dependencies
and install wordpress application from wordpress sources

make sure all php libraries for wordpress are installed.

**Comment by cloudwm** [comment]
Create the wordpress database and configure it in the wp-config.php automaticaly.

**Comment by cloudwm** [comment]
The variables of the cwm should be taken from what is set in the startup-cwm.sh script.

**Comment by nadavg-omc** [comment]
- mysql configuration needs to use defaults config file instead of userpass in commandline
- env variables should be used instead of generating them manually
- descriptions are missing from the main script
