### ISSUE TITLE
cPanel/WHM | lfd Issue

### ISSUE THREAD

**Issue by NeoLoger** [cloudwm/installer#327]
When creating new cPanel/WHM server and selecting the:
cpanelwhm-csf-cmc-liveinstall-centos7.4 64bit-minimal

There is a problem in the file **/etc/csf/regex.custom.pm**
The script is creating the first 2 lines wrong
```
#!/usr/local/cpanel/3rdparty/bin/perl

sub custom_line {
    my  = shift;
    my  = shift;
```
It is supposed to be :
```
#!/usr/local/cpanel/3rdparty/bin/perl
 
 
sub custom_line {
    my $line = shift;
    my $lgfile = shift;
```

This is braking the LFD in the server and preventing from the CSF blocking attacks properly.
Attaching the correct **regex.custom.pm** file
[regex.custom.pm.txt](https://github.com/cloudwm/installer/files/3605507/regex.custom.pm.txt)

**Comment by cloudwm** [comment]
The failure was due to a special character issue. The live install script generates nested install scripts which require different escaping sequences.
