### ISSUE TITLE
services/ntpd

### ISSUE THREAD

**Issue by cloudwm** [cloudwm/installer#59]
setup ntpd and enable service that will automatically update the time on server.

**Comment by nadavg-omc** [comment]
ntpd may be the most veteran way for time handling, but why not Chrony? It has some advantages for virtual servers:
https://chrony.tuxfamily.org/comparison.html
https://www.thegeekdiary.com/centos-rhel-7-chrony-vs-ntp-differences-between-ntpd-and-chronyd/

**Comment by cloudwm** [comment]
This is meaningless for such service, we'll use the classic, known ntpd.
