### ISSUE TITLE
installer-contrib-lemp.conf

### ISSUE THREAD

**Issue by cloudwm** [cloudwm/installer#72]
Create a installer-contrib-lemp.conf for generic 

Configure mysql-autoconfig,conf & php-fpm-autoconfig.conf  50/50 in resources.

**Comment by nadavg-omc** [comment]
> Configure mysql-autoconfig,conf & php-fpm-autoconfig.conf 50/50 in resources.

what is meant by 50/50 in resources? please be specific or provide a reference

**Comment by cloudwm** [comment]
In the autoconfig files of the mysql and php, you can set the amount of resources each service will consume in RAM and CPU. See the autoconfig files and set it accordingly.
