### ISSUE TITLE
installer-contrib-magento.conf

### ISSUE THREAD

**Issue by cloudwm** [cloudwm/installer#83]

**Comment by nadavg-omc** [comment]
1. USERPASS is redundant, can be optimized
2. move tar gz for magento to source folder and symobic link to latest
3. create extras/magento-nginx folder and write properly

**Comment by nadavg-omc** [comment]
default nginx configuration isn't secure enough, we should be using the following:
`location / {
    root $MAGE_ROOT;
    try_files $uri $uri/ /index.php$is_args$args;
    fastcgi_pass   fastcgi_backend;
    fastcgi_buffers 1024 4k;

    fastcgi_param  PHP_FLAG  "session.auto_start=off \n suhosin.session.cryptua=off";
    fastcgi_param  PHP_VALUE "memory_limit=756M \n max_execution_time=18000";
    fastcgi_read_timeout 600s;
    fastcgi_connect_timeout 600s;

    fastcgi_index  index.php;
    fastcgi_param  SCRIPT_FILENAME  $document_root$fastcgi_script_name;
    include        fastcgi_params;
}
`
